# Mod Options
modId=dialogue
modName=DialogueToolBox
modVersion=0.0.0
modAuthor=dan_bat
license=MIT

# Libraries
hollowcore=2.3.17
kotlinVersion=2.2.0
koolVersion=0.18.0-0mods-SNAPSHOT
compiler_plugin=1.5.1

# Mod publishing
publish.modrinth=
publish.curseforge=

# Gradle properties
org.gradle.jvmargs=-Xmx6096m -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.daemon=false
